routes/web.php
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('error-logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    include 'admin/users.php';
    include 'admin/employees.php';
    include 'admin/roles.php';
    include 'admin/categories.php';
    include 'admin/brands.php';
    include 'admin/services.php';
    include 'admin/products.php';
    include 'admin/regions.php';
    include 'admin/cities.php';
    include 'admin/ads.php';
    include 'admin/offers.php';
    include 'admin/coupons.php';
    include 'admin/notification_bar.php';
    include 'admin/centers.php';
    include 'admin/shippings.php';
    include 'admin/payments.php';
    include 'admin/orders.php';
    include 'admin/order_status.php';
    include 'admin/bank_accounts.php';
    include 'admin/banks.php';
    include 'admin/invoices.php';
    include 'admin/returns.php';
    include 'admin/campaings.php';
    include 'admin/notifications.php';
    include 'admin/reports.php';
    include 'admin/expense_type.php';
    include 'admin/expenses.php';
    include 'admin/supports.php';
    include 'admin/settings.php';
    include 'admin/contact_us.php';
    include 'admin/online_payment_logs.php';
});

///////////////////////////////////////// Begin Web routes /////////////////////////////

$langObj = new \Mcamara\LaravelLocalization\LaravelLocalization();
$prefix =  $langObj->setLocale();

Route::group(['namespace' => 'Web',
    'middleware' => ['web','localeSessionRedirect', 'localizationRedirect', 'localeViewPath','localeCookieRedirect'],
    'prefix' => $prefix
], function () {

    Route::get('forget-password', 'Auth\ForgotPasswordController@forgetPassword')->name('forgetPassword');
    Route::post('send-code', 'Auth\ForgotPasswordController@sendCode')->name('sendCode');
    Route::get('change-password', 'Auth\ForgotPasswordController@confirmPassword')->name('changePassword');
    Route::post('reset-password', 'Auth\ForgotPasswordController@changePassword')->name('resetPassword');

    // Verification Code
    Route::get('verify-account', 'Auth\RegisterController@showVerifyForm')->name('verify-code');
    Route::post('verify', 'Auth\RegisterController@verify_account')->name('send-code');
    Route::get('resend-code', 'Auth\RegisterController@resend_code')->name("resend.code");
    Route::get('account-activate/{user}', 'Auth\RegisterController@accountActivate')->name('account-activate');

    Route::post('save-address', 'IndexController@saveShipping')->name('save_address');

    Route::post('save-contact', 'IndexController@saveContact')->name('save_contact');

    Route::get('get-city', 'IndexController@getCity')->name('getCity');

    Route::get('get-fees', 'CheckoutController@getFees')->name('getFees');

    Auth::routes();

    Route::get('logout', 'Auth\LoginController@logout')->name("logout");

    Route::get('/', 'IndexController@index')->name("webHome");

    Route::get('delete-add', 'IndexController@deleteAd')->name("delete.ad");

    Route::get('profile', 'IndexController@profile')->name("profile");

    Route::post('update-profile', 'IndexController@updateProfile')->name("updateProfile");

    Route::get('locations', 'IndexController@locations')->name("locations");

    Route::get('transactions', 'IndexController@transactions')->name("transactions");

    Route::get('messages', 'IndexController@messages')->name("messages");

    Route::get('get-messages', 'IndexController@getMessages')->name("get.messages");

    Route::get('notifications', 'IndexController@notifications')->name("notifications");

    Route::get('get-notifications', 'IndexController@getNotifications')->name("get.notifications");

    Route::get('about-us', 'IndexController@about')->name("about_us");

    Route::post('ajax-get-cities', 'CheckoutController@getCities')->name('checkout.cities');

    Route::post('ajax-get-valid-cities', 'CheckoutController@getCitiesWithCenters')->name('checkout.cities.centers');


    Route::group(['prefix' => 'products'], function () {

     Route::get('category/{slug}', 'ProductsController@categoryProducts')->name("products.category");

     Route::get('brand/{row}', 'ProductsController@brandProducts')->name("products.brand");

     Route::get('offer/{row}', 'ProductsController@offerProducts')->name("products.offer");

     Route::get('new-arrivals', 'ProductsController@newProducts')->name("products.new");

     Route::get('featured-arrivals', 'ProductsController@featuredProducts')->name("products.featured");

     Route::get('add-wishlist/{product}', 'ProductsController@addWishlist')->name("products.add.wishlist");

     Route::get('delete-wishlist/{product}', 'ProductsController@deleteWishlist')->name("products.delete.wishlist");

     Route::get('add-cart/{product}/{price}', 'ProductsController@addCart')->name("products.add.cart");

     Route::get('delete-cart/{cart}', 'ProductsController@deleteCart')->name("products.delete.cart");

     Route::post('apply-coupon', 'ProductsController@applyCoupon')->name("products.apply.coupon");

     Route::get('details/{slug}', 'ProductsController@details')->name("products.details");

     Route::get('related/{slug}', 'ProductsController@related')->name("products.related");

     Route::get('most-sold', 'ProductsController@mostSold')->name("products.most_sold");

        Route::get('latest-products', 'ProductsController@latestProducts')->name("products.latest");

     Route::get('search-result', 'ProductsController@search')->name("products.search");

        Route::get('clear-search', 'ProductsController@clearSearch')->name("products.clear_search");

        Route::get('clear-feature', 'ProductsController@clearFeature')->name("products.clear_feature");

        Route::get('clear-latest', 'ProductsController@clearLatest')->name("products.clear_latest");

        Route::get('clear-new', 'ProductsController@clearNew')->name("products.clear_new");

        Route::get('clear-relate', 'ProductsController@clearRelate')->name("products.clear_related");

        Route::get('clear-most', 'ProductsController@clearMost')->name("products.clear_most");

     Route::get('wishlist', 'ProductsController@wishlist')->name("products.wishlist");

     Route::get('cart', 'ProductsController@cart')->name("products.cart");

     Route::get('remove-item', 'ProductsController@removeItem')->name("products.removeItem");

     Route::get('refresh-cart', 'ProductsController@refreshCart')->name("products.refresh.cart");

     Route::get('more-reviews', 'ProductsController@moreReviews')->name('products.more.reviews');

     Route::get('get-colors', 'ProductsController@getColors')->name('products.get_colors');

        Route::get('get-image', 'ProductsController@getImage')->name('products.get_image');


        Route::get('get-filter-category', 'ProductsController@filterCategory')->name('products.filter.category');

     Route::get('get-filter-brand', 'ProductsController@filterBrand')->name('products.filter.brand');

     Route::get('get-filter-featured', 'ProductsController@filterFeatured')->name('products.filter.featured');

     Route::get('get-filter-new', 'ProductsController@filterNew')->name('products.filter.new');

     Route::get('get-filter-offer', 'ProductsController@filterOffer')->name('products.filter.offer');

     Route::get('get-filter-sold', 'ProductsController@filterSold')->name('products.filter.sold');

     Route::get('get-filter-related', 'ProductsController@filterRelated')->name('products.filter.related');

     Route::get('get-filter-search', 'ProductsController@filterSearch')->name('products.filter.search');

     Route::get('add-item-cart', 'ProductsController@addItemCart')->name("products.add.item.cart");

     Route::get('add-item-wishlist', 'ProductsController@addItemWishlist')->name("products.add.item.wishlist");

     Route::get('add-quantity', 'ProductsController@addQuantity')->name("products.add.quantity");

     Route::get('minus-quantity', 'ProductsController@minusQuantity')->name("products.minus.quantity");

     Route::get('total-cart', 'ProductsController@totalCart')->name("products.get.total.cart");

    });

    Route::group(['prefix' => 'offers'], function () {

        Route::get('all-offers', 'OffersController@index')->name("web:offers.index");

    });

    Route::group(['prefix' => 'checkout' , 'middleware' => 'auth'], function () {

        Route::get('index', 'CheckoutController@index')->name("checkout.index");

        Route::get('get-form', 'CheckoutController@getForm')->name("checkout.get_form");

        Route::get('get-centers', 'CheckoutController@getCenters')->name("checkout.get_centers");

        Route::get('add-shipping', 'CheckoutController@addShipping')->name("checkout.add_shipping");

        Route::get('get-nearest-centers', 'CheckoutController@getNearest')->name("checkout.get_nearest_centers");

        Route::post('save-shipping', 'CheckoutController@saveShipping')->name("checkout.save_shipping");

        Route::get('edit-shipping/{shipping}', 'CheckoutController@editShipping')->name("checkout.edit_shipping");

        Route::post('update-shipping/{id}', 'CheckoutController@updateShipping')->name("checkout.update_shipping");

        Route::delete('delete-shipping/{shipping}', 'CheckoutController@deleteShipping')->name("checkout.delete_shipping");

        Route::get('payment', 'CheckoutController@payment')->name("checkout.payment");

        Route::get('payment/get_status', 'PaymentsController@getStatus')->name("payment.get_status");

        Route::post('payment/get_payment_form_type', 'CheckoutController@getPaymentFormType')->name("payment.visa_type_ajax");
    });

    Route::group(['prefix' => 'payment'], function () {

        Route::get('get-bank-info', 'PaymentsController@getData')->name("payments.get_bank_info");

        Route::get('get-payment-type', 'PaymentsController@getType')->name("payments.get_payment_type");

app/Models/Ad.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\App;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use Spatie\Translatable\HasTranslations;

class Ad extends Model implements HasMedia
{

    use  SoftDeletes, HasTranslations, HasMediaTrait;

    public $table = 'ads';

    protected $dates = [
        'updated_at',
        'created_at',
        'deleted_at'
    ];
    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = ['img'];

    protected $fillable = [
        'title_en',
        'description_en',
        'title_ar',
        'description_ar',
        'image_path',
        'location',
        'product_id',
        'start_date',
        'end_date',
        'category_id',
        'offer_id',
        'location',
        'sub_location'

    ];

    public function registerMediaCollections()
    {
        $this->addMediaCollection('ad')
            ->singleFile();
    }
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')->width(50)->height(50);
    }
    public function getImgAttribute()
    {
        $file = $this->getMedia('ad')->last();

        if ($file) {
            $file->url = $file->getUrl();
            $file->thumbnail = $file->getUrl('thumb');
            $file->localUrl = asset('storage/'.$file->id.'/'.$file->file_name);
        }

        return $file;
    }

    public function getTitleAttribute()
    {
        return App::getLocale() == 'ar' ? $this->title_ar : $this->title_en;

    }

    public function getDescriptionAttribute()
    {

        return App::getLocale() == 'ar' ? $this->description_ar : $this->description_en;

    }

}

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{

    protected $table = "messages";
    protected $fillable = ["name","email","phone","message","status"];
}

resources/views/web/messages/get_messages.blade.php
@foreach($messages as $msg)
    <div class="notification">
        <div class="not-img">
            @if($msg->type == 0)
                <img class="img-fluid" src="{{url('web/assets/img/notf.webp')}}" alt="">
            @elseif($msg->type == 1)
                <img class="img-fluid" src="{{url('web/assets/img/sms.png')}}" alt="">
            @else
                <img class="img-fluid" src="{{url('web/assets/img/email1.png')}}" alt="">
            @endif
        </div>
        <div class="not-text">
            <h6>{{$msg->title}}</h6>
            <p>{{$msg->message}}</p>
        </div>
    </div>
@endforeach
@if(count($messages) > 9)
<div class="notification-but">
    <button onclick="getMessages({{count($messages)}})">
        <span>Show more</span>
        <img src="{{url('web/assets/img/chevron-down.svg')}}" alt="">
    </button>
</div>
@endif

resources/views/web/messages/index.blade.php
@extends("web.master")
@section("header")
    @include("web.partials.header")
@endsection
@section("content")
    <!-- start  Breadcrumb-->
<div class="container">
    <div class="item-breadcrumb">
        <ul>
            <li>{{__('translated_web.home')}}</li>
            <li>{{__('translated_web.messages')}}</li>
        </ul>
    </div>
</div>
<!-- end  Breadcrumb-->
<!-- start account -->
<div class="my-account">
    <div class="container">
        <div class="row">
            @include('web.partials.sidebar')

            <div class="col-12 col-md-12 col-lg-9" id="result">

                @if(count($messages) == 0)
                    <div class="alert alert-success" role="alert">
                        <h3 style="text-align: center">{{__('translated_web.data_not_found')}}</h3>
                    </div>
                @endif

                @foreach($messages as $msg)
                <div class="notification">
                    <div class="not-img">
                        @if($msg->type == 0)
                        <img class="img-fluid" src="{{url('web/assets/img/notf.webp')}}" alt="">
                       @elseif($msg->type == 1)
                            <img class="img-fluid" src="{{url('web/assets/img/sms.png')}}" alt="">
                        @else
                            <img class="img-fluid" src="{{url('web/assets/img/email1.png')}}" alt="">
                        @endif
                    </div>
                    <div class="not-text">
                        <h6>{{$msg->title}}</h6>
                        <p>{{$msg->message}}</p>
                    </div>
                </div>
                @endforeach
                    @if(count($messages) > 9)
                    <div class="notification-but">
                        <button onclick="getMessages({{count($messages)}})">
                            <span>Show more</span>
                            <img src="{{url('web/assets/img/chevron-down.svg')}}" alt="">
                        </button>
                    </div>
                    @endif
            </div>
        </div>
    </div>
</div>

    <script src="{{url('web/assets/js/jquery-3.4.1.min.js')}}"></script>

    <script>

        function getMessages(total){
            $.ajax({

                method: 'Get',
                url: "{{route('get.messages')}}",
                data: {
                    total: total,
                },
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                success: function (data) {
                    $('#result').html(data);
                }
            });
        }

    </script>

@endsection
@section("footer")
    @include("web.partials.footer")
@endsection

@section("js")


@endsection